### ISSUE TITLE
E4S-Documenter no longer correctly detects Accelerator Variants with new Spack

### ISSUE THREAD

**Issue by bonachea** [E4S-Project/E4S-Documenter#8]
## Summary 

As of Dec 4 2023, the E4S-Documenter no longer correctly detects Accelerator Variants from the output of `spack info`, resulting in garbled/incorrect output on https://e4s-project.github.io/DocPortal.html

## Example package, before Dec 4 2023:

![e4s-doc-upcxx-before](https://github.com/E4S-Project/E4S-Documenter/assets/7160884/72699300-2532-46d0-b2fa-8812d226ccc0)

## Same package, after Dec 4 2023:

![e4s-doc-upcxx-after](https://github.com/E4S-Project/E4S-Documenter/assets/7160884/ef1714c0-4658-4854-be33-e24a1060212c)

### Observations

Note the Accelerator Variants field no longer correctly lists the supported variants, despite the fact the spack variants for this package have not changed. Further, this defect is not specific to one package - I believe all packages with previously non-empty Accelerator Variants have been subjected to similar corruption.

## Analysis

I believe the root cause of the problem is the variant output of `spack info` recently underwent major reformatting changes, see [Spack PR 40998](https://github.com/spack/spack/pull/40998). E4S-Documenter parses this output to detect Accelerator Variants, and as a result of the formatting changes the parsing logic is no longer correct.

Specifically, [this line](https://github.com/E4S-Project/E4S-Documenter/blob/99f5e62c0b6c30c851d86c1120f17d2050866665/bin/DocPortalGen.py#L177) in the parsing logic assumes there is a blank line in the `spack info` output between the text `Variants:` and the start of the variant list. However, that blank line has been removed (see images in [Spack PR 40998](https://github.com/spack/spack/pull/40998)). As a result, the parsing logic now entirely skips the block of text containing the spack variants and instead searches the next section of the `spack info` output, which varies by package. In the package shown above that section happens to be the info regarding a `when +cuda` conditional variant, which is why the string "cuda" was still found (by chance) and `Accelerator Variants: CUDA` was printed. In other packages that next info section can be something completely different that doesn't happen to contain any textual references to accelerators, resulting in blank output for Accelerator Variants.

**Comment by wspear** [comment]
Thanks for the report and in depth examination of this issue. The accelerator variant parser should be fixed and those fixes should be reflected on e4s.io now.

**Comment by bonachea** [comment]
Confirmed!

Thanks for the quick fix @wspear !
